/* CHALLENGE 12: GROUP BY
/* Nombre: Marcos Dominguez Vega | Expediente:228 */
/* Ejercicio 1: Introduccion GROUP BY */
/* PASO 1*/

SELECT vnt.fechaVenta, vnt.totalventa
FROM venta vnt
LIMIT 2;

/* PASO 2*/

SELECT vnt.totalVenta, vnt.fechaVenta
FROM venta vnt
WHERE vnt.fechaVenta BETWEEN "2023-01-01" AND "2023-12-31"
LIMIT 2;

/*PASO 3*/

SELECT COUNT(vnt.idVenta) ventas
FROM venta vnt
LIMIT 3;

/* AGREGO OLA FUNCION COUN PARA CONTAR CADA UNO DE LOS VALORES DE LA COLUMNA idVenta*/

/* PASO 4*/

SELECT COUNT(vnt.idVenta) ventas ,vnt.fechaVenta
FROM veta vnt;


/*PASO 5*/
SELECT COUNT(vnt.idVenta) ventas, vnt.fechaventa
FROM venta vnt
GROUP BY vnt.fechaVenta
LIMIT 3;
/* PASO 6:
LO QUE SUCEDE AQUI ES QUE CUANDO SELECCIONAMOS LA FECHA Y SU TOTAL, AL PRINCIPIO
SELECCIONA TODOS LOS REGISTROS SIN IMPORTAR SI SON REPETIDOS O NO PODRIAMOS TENER QUE UNA
VENTA ES REALIZADA 2 VECES EL MISMO DIA, POR ESTA RAZON EN EL PASO 4 RECIBIREMOS UNA SALIDA DE ERROR
PORQUE LA COLUMNA DEVUELVE VARIOS VALORES, PARA EVITAR ESTO USAMOS EL GROUP BY QUE AGRUPA LAS VENTAS HECHAS SEGUN SU FEHA
*/
